<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'BaseController' => $baseDir . '/app/controllers/BaseController.php',
    'CreateQuotes' => $baseDir . '/app/database/migrations/2013_12_13_180355_create_quotes.php',
    'DatabaseSeeder' => $baseDir . '/app/database/seeds/DatabaseSeeder.php',
    'HomeController' => $baseDir . '/app/controllers/HomeController.php',
    'IlluminateQueueClosure' => $vendorDir . '/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php',
    'PeopleController' => $baseDir . '/app/controllers/PeopleController.php',
    'Person' => $baseDir . '/app/models/Person.php',
    'PersonsToPeopleName' => $baseDir . '/app/database/migrations/2013_12_13_203048_persons_to_people_name.php',
    'Product' => $baseDir . '/app/models/Product.php',
    'ProductsController' => $baseDir . '/app/controllers/ProductsController.php',
    'Quote' => $baseDir . '/app/models/Quote.php',
    'QuotesController' => $baseDir . '/app/controllers/QuotesController.php',
    'SessionHandlerInterface' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
    'TestCase' => $baseDir . '/app/tests/TestCase.php',
    'Type' => $baseDir . '/app/models/Type.php',
    'TypesController' => $baseDir . '/app/controllers/TypesController.php',
    'User' => $baseDir . '/app/models/User.php',
);
